<a href="https://colab.research.google.com/github/Mythili134/P.-Mythili/blob/main/DL_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
X = [[1,2,3],
    [4 ,5,6],
    [9 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = [[X[i][j] + Y[i][j]  for j in range
(len(X[0]))] for i in range(len(X))]

for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[12, 10, 10]


In [2]:
import numpy as np
A = [[1, 3, 3],
    [4, 3, 6],
    [7, 4, 5]]

B = [[5, 8, 1, 2],
    [6, 7, 0, 0],
    [1, 5, 9, 1]]

result= [[0,0,0,0],
        [0,0,0,0],
        [2,3,0,0]]

result = np.dot(A,B)

for r in result:
    print(r)

[26 44 28  5]
[44 83 58 14]
[ 64 109  52  19]


In [3]:
X = [[2,2,3],
    [3 ,5,6],
    [9,8,9],
     [4,5,6]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1],
     [4,5,6]]


result = [[0,0,0],
         [0,0,0],
         [9,0,0],
          [0,0,0]]
for i in range(len(X)):
   for j in range(len(X[0])):
       result[i][j] = X[i][j] * Y[i][j]

for r in result:
     print(r)

[18, 16, 21]
[18, 25, 24]
[27, 16, 9]
[16, 25, 36]


In [4]:
N, M = 4, 4
def printIntersection(A, B):
    for i in range(M):
        for j in range(N):
            if (A[i][j] == B[i][j]) :
                print(A[i][j], end = " ")
            else :
                print("* ", end = " ")

        print()
if __name__ == "__main__" :

    A = [ [2, 4, 6, 8 ],
        [ 1, 3, 5, 7 ],
        [ 8, 6, 4, 2 ],
        [ 7, 5, 3, 1 ] ]

    B = [ [ 2, 3, 6, 8 ],
        [ 1, 3, 1, 2 ],
        [ 8, 1, 4, 2 ],
        [ 7, 5, 3, 9 ] ]

    printIntersection(A, B)

2 *  6 8 
1 3 *  *  
8 *  4 2 
7 5 3 *  


In [5]:
import numpy as np
matrix_a = np.matrix([[4, 2, 4], [3, 4, 5]])
matrix_b = np.matrix([[5, 6, 7], [7, 8, 9]])
matrix_c = np.matrix([[5,7,9],[9,5,4]])
result = matrix_a * matrix_b.transpose()

print("Result of Matrix Multiplication:")
print(result)


Result of Matrix Multiplication:
[[60 80]
 [74 98]]


In [6]:
N, M = 3, 3
def printIntersection(A, B):
    for i in range(M):
        for j in range(N):
            if (A[i][j] == B[i][j]) :
                print(A[i][j], end = " ")
            else :
                print("# ", end = " ")

        print()
if __name__ == "__main__" :

    A = [ [2, 4, 6 ],
        [ 1, 3, 5  ],
        [ 8, 6, 4  ]]

    B = [ [ 2, 3,4 ],
        [ 1, 3, 1 ],
        [ 8, 1, 4 ]]

    printIntersection(A, B)

2 #  #  
1 3 #  
8 #  4 
